# Generated by Django 2.2.5 on 2019-10-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nosotros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={'verbose_name': 'Contenido', 'verbose_name_plural': 'Contenido'},
        ),
    ]
