# Generated by Django 2.2.5 on 2019-11-09 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electronico')),
                ('telefono', models.IntegerField(verbose_name='Celular')),
                ('cantidad_personas', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de personas')),
                ('hora_reserva', models.TimeField(verbose_name='Nombre')),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('NO_CONFIRMADA', 'No confirmada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Candelada')], default='NO_CONFIRMADA', max_length=30)),
                ('motivo', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Reservacion',
                'verbose_name_plural': 'Reservaciones',
            },
        ),
    ]
