# Generated by Django 2.2.5 on 2019-11-09 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='created',
        ),
        migrations.RemoveField(
            model_name='reservacion',
            name='updated',
        ),
    ]
