# Generated by Django 2.2.5 on 2019-11-14 03:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0002_auto_20191109_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='hora_reserva',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='El telefono debe ingresarse como +569XXXXXXXX', regex='/^(\\+?56)?(\\s?)(0?9)(\\s?)[9876543]\\d{7}$/')]),
        ),
    ]
