# Generated by Django 2.2.5 on 2019-11-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0003_auto_20191114_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='telefono',
            field=models.IntegerField(verbose_name='Celular'),
        ),
    ]
