# Generated by Django 2.2.5 on 2019-11-14 03:45

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0004_auto_20191114_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='telefono',
            field=phone_field.models.PhoneField(max_length=31, verbose_name='Celular'),
        ),
    ]
