# Generated by Django 2.2.5 on 2019-11-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0005_auto_20191114_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='telefono',
            field=models.IntegerField(verbose_name='Celular'),
        ),
    ]
