# Generated by Django 2.2.5 on 2019-11-21 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0006_auto_20191114_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='telefono',
            field=models.IntegerField(max_length=9, verbose_name='Celular'),
        ),
    ]
