# Generated by Django 2.2.5 on 2019-11-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0007_auto_20191121_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='telefono',
            field=models.IntegerField(verbose_name='Celular'),
        ),
    ]
