# Generated by Django 2.2.5 on 2019-11-21 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservacion', '0009_auto_20191121_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='cantidad_personas',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Personas'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='estado',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('NO_CONFIRMADA', 'No confirmada'), ('REALIZADA', 'Realizada'), ('CANCELADA', 'Candelada')], default='NO_CONFIRMADA', max_length=30, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
