# Generated by Django 2.2.5 on 2019-11-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenido',
            options={'ordering': ['-titulo'], 'verbose_name': 'Contenido', 'verbose_name_plural': 'Contenido'},
        ),
        migrations.AlterModelOptions(
            name='galeria',
            options={'ordering': ['-titulo'], 'verbose_name': 'Galeria', 'verbose_name_plural': 'Galeria'},
        ),
        migrations.AlterModelOptions(
            name='plato',
            options={'ordering': ['tipo_plato'], 'verbose_name': 'Plato', 'verbose_name_plural': 'Platos'},
        ),
    ]
