# Generated by Django 2.2.5 on 2019-11-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191110_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Plato'),
        ),
        migrations.AlterField(
            model_name='plato',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
    ]
