# Generated by Django 2.2.5 on 2019-11-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191121_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoplato',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Tipo de Plato'),
        ),
    ]
