# Generated by Django 2.2.5 on 2019-11-21 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191121_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plato',
            name='tipo_plato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.TipoPlato', verbose_name='Tipo de Plato'),
        ),
    ]
