# Generated by Django 2.2.5 on 2019-10-24 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0002_auto_20191023_2257'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carta',
            options={'verbose_name': 'Carta', 'verbose_name_plural': 'Carta'},
        ),
    ]
