# Generated by Django 2.2.5 on 2019-10-24 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0003_auto_20191024_0110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carta',
            new_name='Plato',
        ),
        migrations.AlterModelOptions(
            name='plato',
            options={'verbose_name': 'Plato', 'verbose_name_plural': 'Platos'},
        ),
    ]
